name: Build script for OnePlus 13

on:
  workflow_dispatch:
    inputs:
      CPU:
        description: 'CPU'
        required: true
        type: string
        default: sm8750
      FEIL:
        description: 'FEIL'
        required: true
        type: string
        default: oneplus_13
      ANDROID_VERSION:
        description: 'Android Version'
        required: true
        type: string
        default: android15
      KERNEL_VERSION:
        description: 'Kernel Version'
        required: true
        type: string
        default: 6.6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup System
        run: |
          sudo apt update
          sudo apt install -y bc build-essential zip curl git gnupg flex bison libssl-dev python3 python3-pip ccache

      - name: Install Repo
        run: |
          mkdir -p ~/bin
          curl -sSL https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "export PATH=~/bin:$PATH" >> $GITHUB_ENV

      - name: Initialize and sync kernel source
        run: |
          repo init -u https://github.com/JiuGeFaCai/kernel_manifest.git -b refs/heads/oneplus/${{ github.event.inputs.CPU }} -m ${{ github.event.inputs.FEIL }}.xml --depth=1
          repo sync -c --no-clone-bundle --no-tags --optimized-fetch -j$(nproc --all) --fail-fast

      - name: Clone SUSFS
        run: |
          git clone https://github.com/sidex15/ksu_module_susfs.git -b v1.5.7

      - name: Apply SUSFS patches
        run: |
          cp ../ksu_module_susfs/kernel_patches/50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch ./common/
          cp ../ksu_module_susfs/kernel_patches/fs/* ./common/fs/
          cp ../ksu_module_susfs/kernel_patches/include/linux/* ./common/include/linux/
          sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
          sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch
          echo '#include <trace/hooks/fs.h>' >> ./common/fs/namespace.c
          patch -p1 < 50_add_susfs_in_gki-${{ github.event.inputs.ANDROID_VERSION }}-${{ github.event.inputs.KERNEL_VERSION }}.patch || true

      - name: Apply Hide Stuff Patches
        run: |
          cp ../kernel_patches/69_hide_stuff.patch ./common/
          patch -p1 --fuzz=3 < ./common/69_hide_stuff.patch

      - name: Add Kernel Configurations
        run: |
          # SukiSU و SUSFS
          echo "CONFIG_SUKISU=y" >> ./common/arch/arm64/configs/gki_defconfig  # فرض می‌کنم SukiSU این تنظیم رو نیاز داره
          echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./common/arch/arm64/configs/gki_defconfig

          # تنظیمات شبکه (BBR و ECN)
          echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_NF_TARGET_ECN=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./common/arch/arm64/configs/gki_defconfig

          # تنظیمات ZRAM (LZ4)
          echo "CONFIG_ZRAM_DEF_COMP_LZ4=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo 'CONFIG_ZRAM_DEF_COMP="lz4"' >> ./common/arch/arm64/configs/gki_defconfig

          # تنظیمات اضافی
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig

      - name: Force ECN and Optimize TCP
        run: |
          cd ./common/net/ipv4
          sed -i 's/net->ipv4.sysctl_tcp_ecn = 2;/net->ipv4.sysctl_tcp_ecn = 1;/' tcp_ipv4.c
          sed -i 's/net->ipv4.sysctl_tcp_pacing_ss_ratio = 200;/net->ipv4.sysctl_tcp_pacing_ss_ratio = 150;/' tcp_ipv4.c
          sed -i 's/net->ipv4.sysctl_tcp_pacing_ca_ratio = 120;/net->ipv4.sysctl_tcp_pacing_ca_ratio = 110;/' tcp_ipv4.c

      - name: Build the Kernel
        run: |
          cd common
          export ARCH=arm64
          export SUBARCH=arm64
          make O=out gki_defconfig
          make O=out -j$(nproc --all)

      - name: Package the Kernel
        run: |
          mkdir -p AnyKernel3
          cp out/arch/arm64/boot/Image.gz AnyKernel3/
          cd AnyKernel3
          zip -r ../SuKiSu_Kernel_${{ github.event.inputs.ANDROID_VERSION }}_${{ github.event.inputs.KERNEL_VERSION }}.zip .
